#!/bin/bash

#To read a usename from keyboard who's entry will be made in the requested server
read -p "Username : " name
rsa=echo $(cat )
passwd=$(grep -w $name /etc/passwd|sed 's/\/\home\//\/\homes\//g')
home=$(grep -w $name /etc/passwd|sed 's/\/\home\//\/\homes\//g'|cut -d ":" -f6)
uid=$(grep -w $name /etc/passwd|sed 's/\/\home\//\/\homes\//g'|cut -d ":" -f2)
gid=$(grep -w $name /etc/passwd|sed 's/\/\home\//\/\homes\//g'|cut -d ":" -f3)
echo -e "Enter the Server Names: (Please Enter 'DONE' while done providing server list)\n"
sname=not_done
while [ $sname != DONE ]
do
	read  sname
	echo $sname >> servers
done
sed -i '$ d' servers
for i in `cat servers`
do
	ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no $i -l root "sudo -t echo $passwd >> /etc/passwd; mkdir $home; chown -R $uid:$gid $home; cd $home; mkdir .ssh; chown $uid:$gid .ssh; chmod 700 .ssh; cd .ssh; touch authorized_keys; chown $uid:$gid authorized_keys; chmod 600 authorized_keys"
	ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no $i -l root "sudo -t echo $(cat ****/home/bhaskar/*****.ssh/id_rsa.pub)"
done
